/* Floppy//144 Stage 2 headless regression tests. */
#include "floppy144_game_data.h"
#include "floppy144_trigger_engine.h"
#include "floppy144_interaction_engine.h"
#include "floppy144_drawing_runtime.h"
#include "floppy144_run_state.h"
#include "floppy144_world.h"
#include <stdint.h>
#include <stdio.h>
#include <string.h>
static int g_nFailures=0;
#define F144_CHECK(c,m) do{if(!(c)){fprintf(stderr,"FAIL: %s (line %d)\n",(m),__LINE__);++g_nFailures;}}while(0)
static uint32_t CountKind(Floppy144DataRecordKind eKind){uint32_t n=0,u;for(u=0;u<Floppy144GameDataRecordCount();++u){const Floppy144DataRecord*p=Floppy144GameDataRecordAt(u);if(p&&p->eKind==eKind)++n;}return n;}
static void TestLedgers(void){F144_CHECK(CountKind(FLOPPY144_DATA_COLLECTION)==35U,"35 collections");F144_CHECK(CountKind(FLOPPY144_DATA_TRIGGER)==50U,"50 triggers");F144_CHECK(CountKind(FLOPPY144_DATA_INTERACTION)==40U,"40 interactions");F144_CHECK(CountKind(FLOPPY144_DATA_EVIDENCE)==23U,"23 evidence");F144_CHECK(CountKind(FLOPPY144_DATA_ROOM)==11U,"11 rooms");F144_CHECK(CountKind(FLOPPY144_DATA_CONNECTION)==16U,"16 connections");F144_CHECK(CountKind(FLOPPY144_DATA_FURNITURE)==151U,"151 furniture");F144_CHECK(CountKind(FLOPPY144_DATA_FIXTURE)==91U,"91 fixtures");F144_CHECK(CountKind(FLOPPY144_DATA_PHYSICAL_ITEM)==161U,"161 physical items");F144_CHECK(CountKind(FLOPPY144_DATA_COLOUR)==44U,"44 colours");F144_CHECK(CountKind(FLOPPY144_DATA_DRAWING)==24U,"24 drawings");F144_CHECK(CountKind(FLOPPY144_DATA_AMBIENT)==16U,"16 ambient interactions");}
static void TestGenericRoute(void){Floppy144WorldState w;Floppy144RunState s;Floppy144TriggerId t1,t2,t3;Floppy144CollectionId dr;Floppy144WorldReset(&w);Floppy144RunStateReset(&s);F144_CHECK(Floppy144WorldInitialiseArchiveServices(&w),"world archive init");F144_CHECK(Floppy144RunStateInitialiseArchiveServices(&s),"run archive init");t1=Floppy144GameDataTriggerId("T-001");t2=Floppy144GameDataTriggerId("T-002");t3=Floppy144GameDataTriggerId("T-003");dr=Floppy144GameDataCollectionId("DR-01");F144_CHECK(t1<FLOPPY144_TRIGGER_COUNT,"T-001 stable ID resolves");F144_CHECK(Floppy144TriggerTryFire(&w,&s,t1),"T-001 generic fire");F144_CHECK(Floppy144RunStateRoomReconstructed(&s,Floppy144GameDataRoomId("RECEPTION")),"Reception reconstructed");F144_CHECK(Floppy144RunStateRoomReconstructed(&s,Floppy144GameDataRoomId("CORRIDOR")),"Corridor reconstructed");F144_CHECK(Floppy144GameDataCollectionEnabled(&s,"DR-02"),"DR-02 enabled by derived effect");F144_CHECK(Floppy144RunStateBitSet(s.collections,(uint32_t)dr),"fixture restores DR-01");F144_CHECK(Floppy144TriggerTryFire(&w,&s,t2),"T-002 generic fire");F144_CHECK(Floppy144RunStateAct(&s)==FLOPPY144_RUN_ACT_I,"SET_ACT interpreted");F144_CHECK(!Floppy144GameDataConnectionUnlocked(&s,"REC_OFF"),"REC_OFF locked before T-003");F144_CHECK(Floppy144TriggerTryFire(&w,&s,t3),"T-003 generic fire");F144_CHECK(Floppy144GameDataConnectionUnlocked(&s,"REC_OFF"),"connection unlock derived");F144_CHECK(Floppy144GameDataPhysicalItemRevealed(&s,"P-008"),"physical reveal derived");}
static void TestFm23(void){Floppy144WorldState w;Floppy144RunState s;Floppy144WorldReset(&w);Floppy144RunStateReset(&s);F144_CHECK(!Floppy144RunStateIsIsometric(&s),"starts 2D");F144_CHECK(Floppy144RunStateBitSet(s.collections,(uint32_t)Floppy144GameDataCollectionId("TS-10")),"fixture TS-10");F144_CHECK(Floppy144RunStateBitSet(s.collections,(uint32_t)Floppy144GameDataCollectionId("FM-23")),"fixture FM-23");F144_CHECK(Floppy144TriggerTryFire(&w,&s,Floppy144GameDataTriggerId("T-025")),"FM-23 trigger generic fire");F144_CHECK(Floppy144RunStateIsIsometric(&s),"FM-23 switches projection");}
static void TestEvidenceOrder(void){Floppy144WorldState w;Floppy144RunState s;Floppy144InteractionId a,b;Floppy144EvidenceId e;Floppy144WorldReset(&w);Floppy144RunStateReset(&s);a=Floppy144GameDataInteractionId("I-004");b=Floppy144GameDataInteractionId("I-005");e=Floppy144GameDataEvidenceId("E-004");F144_CHECK(Floppy144RunStateFireTrigger(&s,Floppy144GameDataTriggerId("T-014")),"fixture T-014");F144_CHECK(Floppy144InteractionCanRun(&s,b),"second half can run first");F144_CHECK(Floppy144InteractionTryRun(&w,&s,b),"second half runs first");F144_CHECK(!Floppy144RunStateEvidenceEstablished(&s,e),"partial pair not evidence");F144_CHECK(Floppy144RunStateFireTrigger(&s,Floppy144GameDataTriggerId("T-013")),"fixture T-013");F144_CHECK(Floppy144InteractionTryRun(&w,&s,a),"first half runs second");F144_CHECK(Floppy144RunStateEvidenceEstablished(&s,e),"reversed pair resolves evidence");}
static void TestDerivedComposite(void){Floppy144RunState s;Floppy144RunStateReset(&s);F144_CHECK(Floppy144RunStateSetBranch(&s,FLOPPY144_RUN_BRANCH_RECORDS_FIRST),"fixture selects Records branch");F144_CHECK(Floppy144RunStateFireTrigger(&s,Floppy144GameDataTriggerId("T-018")),"fixture marks generated Records endpoint");F144_CHECK(Floppy144GameDataConditionSatisfied(&s,"act_at_least","ACT_II_CORE_COMPLETE"),"Act II complete derived from generated branch graph");}
static void TestMappings(void){uint32_t u,n=0;for(u=0;u<Floppy144GameDataRecordCount();++u){const Floppy144DataRecord*p=Floppy144GameDataRecordAt(u);if(!p||p->eKind!=FLOPPY144_DATA_INTERACTION)continue;F144_CHECK(p->pszB!=NULL,"interaction has physical source");if(p->pszB)F144_CHECK(Floppy144InteractionForPhysicalSource(p->pszB)<FLOPPY144_INTERACTION_COUNT,"physical source maps");++n;}F144_CHECK(n==40U,"all 40 mappings tested");}
static void TestAmbient(void){const Floppy144DataRecord*p=Floppy144GameDataAmbientForDate("P-138",10U,31U);F144_CHECK(p!=NULL,"noticeboard resolves Oct 31");if(p){F144_CHECK(p->pszD&&strcmp(p->pszD,"HALLOWEEN")==0,"Halloween season selected");F144_CHECK(p->pszE&&strstr(p->pszE,"HALLOWE'EN")!=NULL,"Halloween copy present");}}
static void TestDrawing(void){uint32_t px[64U*64U],u;Floppy144Surface s;bool changed=false;memset(px,0,sizeof(px));s.pixels=px;s.width=64U;s.height=64U;F144_CHECK(Floppy144DrawingRuntimeDraw(&s,"DRAW_STANDARD_DESK",4,4,52,52),"drawing recipe interpreted");for(u=0;u<64U*64U;++u)if(px[u]){changed=true;break;}F144_CHECK(changed,"drawing writes pixels");}
int main(void){TestLedgers();TestGenericRoute();TestFm23();TestEvidenceOrder();TestDerivedComposite();TestMappings();TestAmbient();TestDrawing();if(g_nFailures){fprintf(stderr,"\nSTAGE 2 HEADLESS TESTS: FAIL (%d failure%s)\n",g_nFailures,g_nFailures==1?"":"s");return 1;}puts("\nSTAGE 2 HEADLESS TESTS: PASS");return 0;}
